// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx032SQi0LtRQQvSgD60zApOHTiabpjEw',
    appId: '1:65865114045:web:5c1555399d5a969fb872d4',
    messagingSenderId: '65865114045',
    projectId: 'malayalam-learning-app-3a42d',
    authDomain: 'malayalam-learning-app-3a42d.firebaseapp.com',
    storageBucket: 'malayalam-learning-app-3a42d.firebasestorage.app',
    measurementId: 'G-DLTKRFDFKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTwHCbHklU9GSxRiP5drARpAjagnbvQ4',
    appId: '1:65865114045:android:37b992d3077a0e2cb872d4',
    messagingSenderId: '65865114045',
    projectId: 'malayalam-learning-app-3a42d',
    storageBucket: 'malayalam-learning-app-3a42d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNR5Fb_wp37wF8gPiJXJY5jlRLQblnOcA',
    appId: '1:65865114045:ios:f3bf12b69adccd8fb872d4',
    messagingSenderId: '65865114045',
    projectId: 'malayalam-learning-app-3a42d',
    storageBucket: 'malayalam-learning-app-3a42d.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );
}
